# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132M-lyJx01hOYg88oSVBSF0LdCFAXpJu
"""

import pandas as pd
import requests
import io

url = "https://raw.githubusercontent.com/JiaC06/AI/main/moviessssss%20(1).csv"

df = pd.read_csv(io.StringIO(download.decode('utf-8')))


print (df.head())
matrix = df.pivot_table(index='movieId', columns='title', values='rating')



matrix = matrix.fillna(2.5, axis=0)
from sklearn.metrics.pairwise import cosine_similarity
similarity =cosine_similarity(matrix.T)
def get_recommendations(title, similarity=similarity,movies=movies):
  idx = movies[movies['title'] == title].index[0]

  movie_scores = list(enumerate(similarity[idx]))

  sorted_scores = sorted(movie_scores, key=lambda x: x[1], reverse=True)

  top_scores = sorted_scores[1:11]

  movie_indices = [i[0] for i in top_scores]

  return movies['title'].iloc[movie_indices]
get_recommendations('Driving Miss Daisy')

